import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic";
import styled from "styled-components";
const MainPage = dynamic(() => import('../components/pages/Main/Main'), {
  ssr: false,
})

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage/>
    </Container>
  )
}

const Container = styled.div`
  background: rgb(236, 236, 236);
  padding: 0 2em;
  min-height: 100vh;
`

export default Home
