import type { NextPage } from 'next'
import Head from 'next/head'
import styled from "styled-components";
import {Button, Container, Typography} from "@mui/material";
import {Box} from "@mui/system";

const Home: NextPage = () => {
  return (
    <StyledContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{mt: 10, textAlign: 'center'}}>
        <Typography variant={'h2'}>Welcome to the Flickr reranking app</Typography>
        <Typography>This lets you specify criteria what you want to search and this app will try its best to find it.</Typography>
        <Box sx={{display: 'flex', justifyContent: 'center', mt: 5}}>
          <Button href={"/socket"} variant={'contained'} size={'large'} sx={{mx: 2}}>Socket search strategy</Button>
          <Button href={"/normal"} variant={'outlined'} size={'large'} sx={{mx: 2}}>Normal search strategy</Button>
        </Box>
      </Container>
    </StyledContainer>
  )
}

const StyledContainer = styled.div`
  padding: 0 2em;
  min-height: 100vh;
`

export default Home
